// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "greet", input: string, result: string },
    mutations: 
        { key: "createUser", input: string, result: { id: number; name: string } },
    subscriptions: never
};
